"""add_github_webhook_deliveries_and_scan_fields

Revision ID: 62a5783d3735
Revises:
Create Date: 2026-09-16 17:05:01.777051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a5783d3735'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_webhook_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('repository', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('commit_sha', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_webhook_deliveries_delivery_id'), 'github_webhook_deliveries', ['delivery_id'], unique=True)
    op.create_index(op.f('ix_github_webhook_deliveries_received_at'), 'github_webhook_deliveries', ['received_at'], unique=False)
    op.create_index(op.f('ix_github_webhook_deliveries_repository'), 'github_webhook_deliveries', ['repository'], unique=False)
    op.create_index(op.f('ix_github_webhook_deliveries_status'), 'github_webhook_deliveries', ['status'], unique=False)
    op.add_column('scans', sa.Column('repository', sa.String(length=255), nullable=True))
    op.add_column('scans', sa.Column('event_type', sa.String(length=50), nullable=True))
    op.add_column('scans', sa.Column('ref', sa.String(length=255), nullable=True))
    op.add_column('scans', sa.Column('commit_sha', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_scans_event_type'), 'scans', ['event_type'], unique=False)
    op.create_index(op.f('ix_scans_repository'), 'scans', ['repository'], unique=False)
    op.create_index(op.f('ix_scans_started_at'), 'scans', ['started_at'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_started_at'), table_name='scans')
    op.drop_index(op.f('ix_scans_repository'), table_name='scans')
    op.drop_index(op.f('ix_scans_event_type'), table_name='scans')
    op.drop_column('scans', 'commit_sha')
    op.drop_column('scans', 'ref')
    op.drop_column('scans', 'event_type')
    op.drop_column('scans', 'repository')
    op.drop_index(op.f('ix_github_webhook_deliveries_status'), table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_repository'), table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_received_at'), table_name='github_webhook_deliveries')
    op.drop_index(op.f('ix_github_webhook_deliveries_delivery_id'), table_name='github_webhook_deliveries')
    op.drop_table('github_webhook_deliveries')
    # ### end Alembic commands ###
