from fastapi import FastAPI

app = FastAPI(
    title="Rakshak",
    description="AI-Powered DevSecOps Threat Detection Platform",
    version="1.0.0"
)


@app.get("/")
def home():
    return {
        "message": "Rakshak DevSecOps Platform",
        "status": "running"
    }


@app.get("/health")
def health():
    return {
        "status": "healthy"
    }


from trivy_parser import parse_trivy_report
from gitleaks_parser import parse_gitleaks_report
from risk_engine import prioritize_findings
from report_generator import generate_report, print_report, save_report


def main():
    # Security reports generated by CI/CD
    trivy_report = "reports/trivy-results.json"
    trivy_image_report = "reports/trivy-image-results.json"
    gitleaks_report = "reports/gitleaks-results.json"

    # Parse filesystem/dependency vulnerabilities
    trivy_findings = parse_trivy_report(trivy_report)

    # Parse Docker image vulnerabilities
    trivy_image_findings = parse_trivy_report(trivy_image_report)

    # Parse secrets
    gitleaks_findings = parse_gitleaks_report(gitleaks_report)

    # Combine all security findings
    all_findings = (
        trivy_findings
        + trivy_image_findings
        + gitleaks_findings
    )

    # Calculate risk scores and priorities
    prioritized_findings = prioritize_findings(all_findings)

    # Generate unified Rakshak report
    report = generate_report(prioritized_findings)

    # Display report
    print_report(report)

    # Save report as JSON
    save_report(report)


if __name__ == "__main__":
    main()