import re
import subprocess
import tempfile
from pathlib import Path

from app.code_scanner import scan_files
from app.gitleaks_parser import parse_gitleaks_report
from app.trivy_parser import parse_trivy_report


# =========================================================
# EXCLUSION HELPERS
# =========================================================

# Directories to exclude from code scanning (generated/environment/cache/worktree)
# These are DEFINITELY generated artifacts that should never contain
# application source code worth scanning.
EXCLUDED_DIRS = {
    # Virtual environments
    "venv", ".venv", "env", ".virtualenv", "virtualenv",
    # Python caches
    "__pycache__", ".pytest_cache", ".mypy_cache", ".tox", ".coverage",
    # Build artifacts
    "dist", "build", "out", ".next", ".nuxt", ".output",
    # Cache directories
    ".cache", ".parcel-cache", ".turbo", ".vercel",
    # Worktrees / duplicate source
    ".kilo",
    # Version control (redundant with existing .git check, but explicit)
    ".git",
    # Node modules (redundant with existing check, but explicit)
    "node_modules",
}


def _should_exclude_path(path: Path) -> bool:
    """Return True if the path should be excluded from scanning."""
    return any(part in EXCLUDED_DIRS for part in path.parts)


# =========================================================
# COMMAND EXECUTION
# =========================================================

def run_command(command):
    result = subprocess.run(
            command, capture_output=True, text=True, timeout=600, check=False
        )

    return result.stdout, result.stderr, result.returncode


# =========================================================
# TRIVY DEPENDENCY SCAN
# =========================================================

def run_dependency_scan(target_path):
    target = Path(target_path).resolve()

    if not target.exists():
        raise FileNotFoundError(
            f"Scan target not found: {target}"
        )

    with tempfile.NamedTemporaryFile(
        suffix=".json",
        delete=False,
    ) as temp_file:
        report_path = Path(temp_file.name)

    try:
        command = [
            "trivy",
            "fs",
            "--timeout",
            "10m",
            "--format",
            "json",
            "--output",
            str(report_path),
            "--scanners",
            "vuln",
            "--skip-dirs",
            "venv,.venv,env,.virtualenv,virtualenv,__pycache__,.pytest_cache,.mypy_cache,"
            ".tox,.coverage,.cache,.parcel-cache,.turbo,.vercel,.kilo,dist,build,out,"
            ".next,.nuxt,.output,.git,node_modules",
            "--skip-files",
            "trivy-*.json,*.log",
            str(target),
        ]

        _, stderr, return_code = run_command(command)

        if return_code != 0:
            raise RuntimeError(
                f"Trivy dependency scan failed: {stderr}"
            )

        return parse_trivy_report(str(report_path))

    finally:
        if report_path.exists():
            report_path.unlink()


# =========================================================
# GITLEAKS SECRET SCAN
# =========================================================

def run_secret_scan(target_path):
    target = Path(target_path).resolve()

    if not target.exists():
        raise FileNotFoundError(
            f"Scan target not found: {target}"
        )

    with tempfile.NamedTemporaryFile(
        suffix=".json",
        delete=False,
    ) as temp_file:
        report_path = Path(temp_file.name)

    # Create a temporary .gitleaksignore file for this scan
    # to exclude generated/environment/cache/worktree directories
    # and known Rakshak scan-result files.
    gitleaks_ignore_content = """# Generated by Rakshak for this scan only
# Exclude generated/environment/cache/worktree directories
venv/
.venv/
env/
virtualenv/
__pycache__/
.pytest_cache/
.mypy_cache/
.tox/
.cache/
node_modules/
.git/
.kilo/
dist/
build/
out/
.next/
.nuxt/
.output/

# Exclude known Rakshak scan-result files
trivy-*.json
*.log
"""

    gitleaks_ignore_path = target / ".gitleaksignore"
    ignore_created = False
    try:
        # Write temporary .gitleaksignore
        gitleaks_ignore_path.write_text(gitleaks_ignore_content, encoding="utf-8")
        ignore_created = True

        with tempfile.NamedTemporaryFile(
            suffix=".json",
            delete=False,
        ) as temp_file:
            report_path = Path(temp_file.name)

        try:
            command = [
                "gitleaks",
                "detect",
                "--source",
                str(target),
                "--report-format",
                "json",
                "--report-path",
                str(report_path),
                "--exit-code",
                "0",
            ]

            _, stderr, return_code = run_command(command)

            if return_code != 0:
                raise RuntimeError(
                    f"Gitleaks scan failed: {stderr}"
                )

            if not report_path.exists():
                return []

            return parse_gitleaks_report(str(report_path))

        finally:
            if report_path.exists():
                report_path.unlink()

    finally:
        # Clean up the temporary .gitleaksignore file
        if ignore_created and gitleaks_ignore_path.exists():
            try:
                gitleaks_ignore_path.unlink()
            except OSError:
                pass


# =========================================================
# CODE SCAN
# =========================================================

def run_code_scan(target_path):
    target = Path(target_path).resolve()

    if not target.exists():
        raise FileNotFoundError(
            f"Scan target not found: {target}"
        )

    supported_extensions = {
        ".py",
        ".js",
        ".jsx",
        ".ts",
        ".tsx",
        ".java",
        ".c",
        ".cpp",
        ".h",
        ".hpp",
        ".go",
        ".php",
        ".rb",
    }

    files = []

    if target.is_file():
        if target.suffix.lower() in supported_extensions:
            # Also check if file itself should be excluded
            if not _should_exclude_path(target):
                files.append(str(target))

    else:
        for path in target.rglob("*"):
            if not path.is_file():
                continue

            if path.suffix.lower() not in supported_extensions:
                continue

            if _should_exclude_path(path):
                continue

            if path.stat().st_size > 1024 * 1024:
                continue

            files.append(str(path))

    return scan_files(files)


def run_container_scan(image_name):
    if not image_name or any(char.isspace() for char in image_name) or re.search(r"[;&|$`\r\n]", image_name):
        raise ValueError("Invalid container image name")
    with tempfile.NamedTemporaryFile(
        suffix=".json",
        delete=False,
    ) as temp_file:
        report_path = Path(temp_file.name)

    try:
        command = [
            "trivy",
            "image",
            "--timeout",
            "10m",
            "--format",
            "json",
            "--output",
            str(report_path),
            "--scanners",
            "vuln",
            image_name,
        ]

        _, stderr, return_code = run_command(command)

        if return_code != 0:
            raise RuntimeError(
                f"Trivy container scan failed: {stderr}"
            )

        return parse_trivy_report(str(report_path))

    finally:
        if report_path.exists():
            report_path.unlink()